import streamlit as st
import time
import hashlib
import json
import random

def get_fake_ipfs_cid(data):
    """Creates a realistic-looking fake IPFS hash (CID) from any data."""
    # Use sha256 to create a unique hash
    hash = hashlib.sha256(data).hexdigest()
    # Format it to look like a real IPFS CID (Content Identifier)
    return f"ipfs://Qm{hash[:44]}"

def get_fake_tx_hash(data):
    """Creates a realistic-looking fake transaction hash."""
    hash = hashlib.sha256(data.encode()).hexdigest()
    return f"0x{hash}"

# --- 1. Streamlit Page Setup ---
st.set_page_config(page_title="NFT Minting Simulator", layout="wide")
st.title("🤖 NFT Minter Pipeline Simulator")
st.write("This app simulates the entire NFT minting pipeline *without* any real blockchain, wallets, or gas fees. This is for testing the frontend and user flow of your project.")

st.sidebar.header("About")
st.sidebar.info("This app fakes the following steps:\n"
                "1. Uploading Art to IPFS\n"
                "2. Creating NFT Metadata\n"
                "3. Uploading Metadata to IPFS\n"
                "4. Calling a smart contract")

# --- 2. User Input Fields ---
st.header("1. Create Your NFT")
col1, col2 = st.columns(2)

with col1:
    nft_name = st.text_input("Name for your NFT", "My AI Masterpiece")
    nft_description = st.text_area("Description", "This was generated by my awesome AI model.")
    
    # We ask for a wallet address, but just to display it later. No real wallet needed.
    wallet_address = st.text_input("Your (Fake) Wallet Address", "0xAb5801a7D398351b8bE11C439e05C5B3259aec9B")

with col2:
    uploaded_file = st.file_uploader("Upload your image (PNG, JPG)", type=["png", "jpg"])
    
    if uploaded_file:
        st.image(uploaded_file, caption="Your uploaded art", width=300)

st.divider()

# --- 3. The Simulation Logic ---
if st.button("Simulate Minting Process", type="primary", use_container_width=True):
    # Check if all inputs are ready
    if not uploaded_file:
        st.error("Please upload an image file first.")
    elif not nft_name or not nft_description or not wallet_address:
        st.error("Please fill in all the details (Name, Description, Wallet Address).")
    else:
        st.info("Simulation started... No gas fees will be required.")
        
        # --- Step 1: Simulate Image Upload to IPFS ---
        with st.spinner("Step 1/4: Uploading image to decentralized storage (IPFS)..."):
            time.sleep(2) # Fake a 2-second upload
            file_bytes = uploaded_file.getvalue()
            image_cid = get_fake_ipfs_cid(file_bytes)
            st.success("✅ Image 'uploaded' to IPFS!")

        # --- Step 2: Simulate Metadata Creation ---
        with st.spinner("Step 2/4: Creating metadata JSON..."):
            time.sleep(1)
            metadata = {
                "name": nft_name,
                "description": nft_description,
                "image": image_cid,
                "attributes": [
                    {"trait_type": "Simulated", "value": "True"},
                    {"trait_type": "Edition", "value": 1}
                ]
            }
            metadata_json = json.dumps(metadata, indent=4)
            st.success("✅ Metadata JSON created!")

        # --- Step 3: Simulate Metadata Upload to IPFS ---
        with st.spinner("Step 3/4: Uploading metadata to IPFS..."):
            time.sleep(2)
            token_uri = get_fake_ipfs_cid(metadata_json.encode())
            st.success("✅ Metadata 'uploaded' to IPFS! This is your Token URI.")

        # --- Step 4: Simulate Smart Contract Call ---
        with st.spinner(f"Step 4/4: Calling smart contract to mint for {wallet_address[:10]}..."):
            time.sleep(3) # Fake a 3-second blockchain transaction
            fake_tx = get_fake_tx_hash(f"{token_uri}{wallet_address}")
            st.success("✅ Smart contract 'called' and transaction 'mined'!")

        # --- 4. Final Success Output ---
        st.header("🎉 Congratulations, your NFT is minted! (Simulated)")
        st.balloons()
        
        st.subheader("Your (Fake) Minting Receipt:")
        st.text_input("Transaction Hash", fake_tx, disabled=True)
        st.text_input("Token URI (Metadata Link)", token_uri, disabled=True)
        st.text_input("Image Link", image_cid, disabled=True)
        
        st.subheader("Your NFT Metadata:")
        st.json(metadata)
        
        # This link won't work, but it shows the user what a *real* link would look like
        st.markdown(f"**[View on (Simulated) BaseScan](https://sepolia.basescan.org/tx/{fake_tx})**")